# Generated by Django 5.2.4 on 2025-08-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='msku',
            old_name='master_sku_code',
            new_name='msku_code',
        ),
        migrations.AddField(
            model_name='msku',
            name='name',
            field=models.CharField(default='Unnamed Product', max_length=255),
        ),
        migrations.AddField(
            model_name='sku',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
